//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swaksoft.Application.Communicator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Swaksoft.Application.Communicator.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Call Id cannot be null.
        /// </summary>
        internal static string api_CallIdCannotBeNull {
            get {
                return ResourceManager.GetString("api_CallIdCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the {0} configuration.
        /// </summary>
        internal static string api_MissingConfiguration {
            get {
                return ResourceManager.GetString("api_MissingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the SMS operation for {0}.
        /// </summary>
        internal static string api_MissingSmsOperation {
            get {
                return ResourceManager.GetString("api_MissingSmsOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a phone number to send SMS messages.
        /// </summary>
        internal static string api_MissingSmsPhoneNumber {
            get {
                return ResourceManager.GetString("api_MissingSmsPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice call &apos;{0}&apos; is missing.
        /// </summary>
        internal static string api_MissingVoiceCall {
            get {
                return ResourceManager.GetString("api_MissingVoiceCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the voice operation for the given id {0}.
        /// </summary>
        internal static string api_MissingVoiceOperation {
            get {
                return ResourceManager.GetString("api_MissingVoiceOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number: {0}.
        /// </summary>
        internal static string validation_InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("validation_InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot call the {0} phone number..
        /// </summary>
        internal static string verification_CannotCallPhoneNumber {
            get {
                return ResourceManager.GetString("verification_CannotCallPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid call ID: {0}.
        /// </summary>
        internal static string verification_InvalidCallId {
            get {
                return ResourceManager.GetString("verification_InvalidCallId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a verification code for {0} id.
        /// </summary>
        internal static string verification_NoVerificationCode {
            get {
                return ResourceManager.GetString("verification_NoVerificationCode", resourceCulture);
            }
        }
    }
}
