// <auto-generated />
namespace Swaksoft.Infrastructure.Data.SocialMedia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class DataSeed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataSeed));
        
        string IMigrationMetadata.Id
        {
            get { return "201503030409461_DataSeed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
