// <auto-generated />
namespace Swaksoft.Infrastructure.Data.SocialMedia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AddFoursquare : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFoursquare));
        
        string IMigrationMetadata.Id
        {
            get { return "201502180853189_AddFoursquare"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
