// <auto-generated />
namespace Swaksoft.Infrastructure.Data.SocialMedia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddAddrType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAddrType));
        
        string IMigrationMetadata.Id
        {
            get { return "201611191916571_AddAddrType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
